# Generated by Django 6.0.2 on 2026-02-23 18:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alici_email', models.EmailField(max_length=254)),
                ('baslik', models.CharField(max_length=200)),
                ('icerik', models.TextField()),
                ('acilma_tarihi', models.DateTimeField()),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('mail_gonderildi', models.BooleanField(default=False)),
                ('acildi', models.BooleanField(default=False)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('gonderen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
