# Generated by Django 6.0.2 on 2026-02-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesajlar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesaj',
            name='mail_gonderim_zamani',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
