# Generated by Django 6.0.2 on 2026-03-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesajlar', '0002_mesaj_mail_gonderim_zamani'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesaj',
            name='mail_gonderim_zamani',
        ),
        migrations.AlterField(
            model_name='mesaj',
            name='baslik',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
