# Generated by Django 6.0.2 on 2026-03-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesajlar', '0003_remove_mesaj_mail_gonderim_zamani_alter_mesaj_baslik'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesaj',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='mesaj_fotolari/'),
        ),
    ]
