# Generated by Django 6.0.2 on 2026-04-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesajlar', '0004_mesaj_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesaj',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
