# Generated by Django 6.0.2 on 2026-04-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesajlar', '0005_mesaj_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesaj',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='mesaj_sesleri/'),
        ),
    ]
